### ISSUE TITLE
ReverseEngineer1.apk signed incorrectly

### ISSUE THREAD

**Issue by agibson-vrnt** [OWASP/SecurityShepherd#283]
In order to solve "Corporal" "Reverse Engineer 1", the jar needs to be signed by the correct user, but currently it reports "sean"

**Comment by SeanDuggan** [comment]
This sounds like an issue. Will begin investigate shortly, as a potential work around, it's possible the apk on the virtual machine is signed correctly as opposed to the jar provided in the zip

**Comment by agibson-vrnt** [comment]
or could be a BCAK error....

**Comment by agibson-vrnt** [comment]
Note that if you use ReverseEngineere2 apk instead, it yields the desired result.

**Comment by nordbo** [comment]
This is true for "Mobile Reverse Engineer 1" as well, where you are to find the name of the developer. You need to use the ReverseEngineer2.apk, not ReverseEngineer1.apk which stated in the challenge.

**Comment by SeanDuggan** [comment]
This naming issues has been resolved! The new VM can be found among the downloads here: https://github.com/OWASP/SecurityShepherd/releases/tag/v3.0

Thanks @agibson-vrnt  + @nordbo

**Comment by Benanname** [comment]
This problem is back, but worse. all 4 files, -1, 1-1, 2-1, 3-1 now return Sean or Sean=D none of which are the correct key
